### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by JulianKahnert** [Janwillhaus/Podcast-Archiver#3]
It would be great, if you can add a *silent mode* so that all the command line output will be suppressed.

**Comment by Janwillhaus** [comment]
Could be done, but I'd rather use integrated shell functionality, i.e. by piping all outputs to `/dev/null`:

```bash
./podcast_archiver.py -d /Users/janwillhaus/Music/Podcasts -vv -s -u -f feedlist.txt > /dev/null
```
